submit: app
limit: 3
streamers:
  output\Tim Dillon LAYS WASTE To Transportation Secretary\output_dub_final.mp4:
    copyright: 1
    no_reprint: 1
    source: null
    tid: 208
    cover: output\Tim Dillon LAYS WASTE To Transportation Secretary\Tim Dillon LAYS
      WASTE To Transportation Secretary_new.png
    title: '[中配] 炸锅！美知名喜剧人炮轰交通部长，美政府彻底“破防” ‖ 青年土耳其人频道'
    desc_format_id: 0
    topic_id: 1167972
    topic_detail:
      from_topic_id: 1167972
      from_source: arc.web.recommend
    desc: '本频道致力于分享中英双语的时事内容、热点解读与观点碰撞。

      我们希望用更平易近人的方式，一起了解世界，也能为英语学习提供真实有料的素材。

      内容仅供学习与交流，请勿过度解读，更不代表任何立场。观点多元，欢迎理性讨论！

      视频素材来自公开网络与授权资源，如有侵权请私信或留言联系删除。

      如果觉得频道还不错，拜托动动手：点赞、投币、收藏，顺手点个关注！

      更希望得到大家的【充电支持】，这是我们持续更新的最大动力！

    dolby: 1
    lossless_music: 1
    tag: 英语新闻, 英语学习, 川普, 马斯克, 咨询直通车, 社会观察局, 热点深度观察
    dynamic: ''
    dtime: 1764806400
    open-elec: 1
